/**
 * @fileoverview AUTO-GENERATED BY VITE CONFIG
 * 
 * @reason Central Registry & Export Hub.
 * This file is automatically generated by `vite.config.ts` to ensure that 
 * the `MasterInstrumentMap` correctly initializes all 16 default GM synthesizers 
 * at the correct index ranges. It acts as the primary NPM package entry point.
 */
import { decodeBinary, encodeToBinary, encodeToSoA } from './RLO-Transpiler.js';
import { RLOCore as BaseCore } from './Core/RLOCore.js';
import { RLOMusicPlayer as BaseMusicPlayer } from './Players/RLOMusicPlayer.js';
import { RLOGameEngine as BaseGameEngine } from './Players/RLOGameEngine.js';
import { createInstrumentMap, extendInstrumentMap, createDirectMap, SilentSynth } from './Core/InstrumentMap.js';
import type { ISynthInstrument } from './Instruments/ISynthInstrument.js';
import { PianoSynth } from './Instruments/Decay/PianoSynth.js';
import { ChromaticPercussionSynth } from './Instruments/Decay/ChromaticPercussionSynth.js';
import { OrganSynth } from './Instruments/Analog/OrganSynth.js';
import { GuitarSynth } from './Instruments/Decay/GuitarSynth.js';
import { ElectricGuitarSynth } from './Instruments/Decay/ElectricGuitarSynth.js';
import { BassSynth } from './Instruments/Analog/BassSynth.js';
import { StringSynth } from './Instruments/Analog/StringSynth.js';
import { BrassSynth } from './Instruments/Decay/BrassSynth.js';
import { WoodwindSynth } from './Instruments/Analog/WoodwindSynth.js';
import { LeadSynth } from './Instruments/Analog/LeadSynth.js';
import { PadSynth } from './Instruments/Analog/PadSynth.js';
import { SoundEffectsSynth } from './Instruments/Speciality/SoundEffectsSynth.js';
import { EthnicSynth } from './Instruments/Decay/EthnicSynth.js';
import { DrumSynth } from './Instruments/Speciality/DrumSynth.js';
import { FMSynth } from './Instruments/Analog/FMSynth.js';
import { AdditiveSynth } from './Instruments/Decay/AdditiveSynth.js';
import { KarplusSynth } from './Instruments/Decay/KarplusSynth.js';
import { ReeseBassSynth } from './Instruments/Analog/ReeseBassSynth.js';
import { FormantSynth } from './Instruments/Analog/FormantSynth.js';
import { ChiptuneSynth } from './Instruments/Analog/ChiptuneSynth.js';
import { SlapBassSynth } from './Instruments/Decay/SlapBassSynth.js';

// Export all synthesizers (including optional ones) for NPM users
export { PianoSynth, ChromaticPercussionSynth, OrganSynth, GuitarSynth, ElectricGuitarSynth, BassSynth, StringSynth, BrassSynth, WoodwindSynth, LeadSynth, PadSynth, SoundEffectsSynth, EthnicSynth, DrumSynth, FMSynth, AdditiveSynth, KarplusSynth, ReeseBassSynth, FormantSynth, ChiptuneSynth, SlapBassSynth };

const defaultMapModules = [
  { synth: new PianoSynth(), start: 0, end: 7 },
  { synth: new ChromaticPercussionSynth(), start: 8, end: 15 },
  { synth: new OrganSynth(), start: 16, end: 23 },
  { synth: new GuitarSynth(), start: 24, end: 26 },
  { synth: new ElectricGuitarSynth(), start: 27, end: 31 },
  { synth: new BassSynth(), start: 32, end: 39 },
  { synth: new StringSynth(), start: 40, end: 55 },
  { synth: new BrassSynth(), start: 56, end: 71 },
  { synth: new WoodwindSynth(), start: 72, end: 79 },
  { synth: new LeadSynth(), start: 83, end: 87 },
  { synth: new PadSynth(), start: 88, end: 95 },
  { synth: new SoundEffectsSynth(), start: 96, end: 103 },
  { synth: new SoundEffectsSynth(), start: 120, end: 127 },
  { synth: new EthnicSynth(), start: 104, end: 111 },
  { synth: new DrumSynth(), start: 112, end: 119 },
  { synth: new DrumSynth(), start: 128, end: 128 },
];
const defaultMap = createInstrumentMap(defaultMapModules);

const retroMap = createInstrumentMap([
  { synth: new ChiptuneSynth(), start: 0, end: 127 },
  { synth: new DrumSynth(), start: 128, end: 128 }
]);

export { decodeBinary, encodeToBinary, encodeToSoA, createInstrumentMap, extendInstrumentMap, createDirectMap, SilentSynth, defaultMap as MasterInstrumentMap, defaultMap as StandardInstrumentMap, retroMap as RetroInstrumentMap };
export class RLOCore extends BaseCore { constructor(ctx: AudioContext, customMap?: ISynthInstrument[]) { super(ctx, customMap || defaultMap); } }
export class RLOMusicPlayer extends BaseMusicPlayer { constructor(ctx: AudioContext, customMap?: ISynthInstrument[]) { super(ctx, customMap || defaultMap); } }
export class RLOGameEngine extends BaseGameEngine { constructor(ctx: AudioContext, customMap?: ISynthInstrument[]) { super(ctx, customMap || defaultMap); } }
