import { defineConfig } from "vite";
import fs from "fs";
import path from "path";
import { minify } from "terser";

const customTerserOptions = {
  ecma: 2020 as const,
  module: true,
  compress: {
    drop_console: true,
    passes: 3,
    unsafe: true,
    unsafe_math: true, // Forces native JS Math methods to mangle cleanly
  },
  mangle: {
    toplevel: true,
    properties: { regex: /^_/ }, // Squashes all internal engine fields to 1 char
  },
  format: { comments: false },
  sourceMap: true,
};

/**
 * INSTRUMENT REGISTRY
 * Defines all synthesizers and their default MIDI routing ranges.
 * Synths with `isDefault: false` are exported as optional instruments for NPM users,
 * but omitted from the Master Map to prevent default bundle bloat.
 */
const SYNTH_MODULES = [
  // DEFAULT SYNTHS
  {
    name: "PianoSynth",
    path: "./Instruments/Decay/PianoSynth.js",
    ranges: [[0, 7]],
    isDefault: true,
  },
  {
    name: "ChromaticPercussionSynth",
    path: "./Instruments/Decay/ChromaticPercussionSynth.js",
    ranges: [[8, 15]],
    isDefault: true,
  },
  {
    name: "OrganSynth",
    path: "./Instruments/Analog/OrganSynth.js",
    ranges: [[16, 23]],
    isDefault: true,
  },
  {
    name: "GuitarSynth",
    path: "./Instruments/Decay/GuitarSynth.js",
    ranges: [[24, 26]],
    isDefault: true,
  },
  {
    name: "ElectricGuitarSynth",
    path: "./Instruments/Decay/ElectricGuitarSynth.js",
    ranges: [[27, 31]],
    isDefault: true,
  },
  {
    name: "BassSynth",
    path: "./Instruments/Analog/BassSynth.js",
    ranges: [[32, 39]],
    isDefault: true,
  },
  {
    name: "StringSynth",
    path: "./Instruments/Analog/StringSynth.js",
    ranges: [[40, 55]],
    isDefault: true,
  },
  {
    name: "BrassSynth",
    path: "./Instruments/Decay/BrassSynth.js",
    ranges: [[56, 71]],
    isDefault: true,
  },
  {
    name: "WoodwindSynth",
    path: "./Instruments/Analog/WoodwindSynth.js",
    ranges: [[72, 79]],
    isDefault: true,
  },
  {
    name: "LeadSynth",
    path: "./Instruments/Analog/LeadSynth.js",
    ranges: [[83, 87]],
    isDefault: true,
  },
  {
    name: "PadSynth",
    path: "./Instruments/Analog/PadSynth.js",
    ranges: [[88, 95]],
    isDefault: true,
  },
  {
    name: "SoundEffectsSynth",
    path: "./Instruments/Speciality/SoundEffectsSynth.js",
    ranges: [
      [96, 103],
      [120, 127],
    ],
    isDefault: true,
  },
  {
    name: "EthnicSynth",
    path: "./Instruments/Decay/EthnicSynth.js",
    ranges: [[104, 111]],
    isDefault: true,
  },
  {
    name: "DrumSynth",
    path: "./Instruments/Speciality/DrumSynth.js",
    ranges: [
      [112, 119],
      [128, 128],
    ],
    isDefault: true,
  },

  // OPTIONAL SYNTHS (Exported for direct imports, but excluded from the Master map)
  {
    name: "FMSynth",
    path: "./Instruments/Analog/FMSynth.js",
    ranges: [[4, 5]],
    isDefault: false,
  },
  {
    name: "AdditiveSynth",
    path: "./Instruments/Decay/AdditiveSynth.js",
    ranges: [
      [14, 14],
      [98, 98],
      [112, 112],
    ],
    isDefault: false,
  },
  {
    name: "KarplusSynth",
    path: "./Instruments/Decay/KarplusSynth.js",
    ranges: [[24, 25]],
    isDefault: false,
  },
  {
    name: "ReeseBassSynth",
    path: "./Instruments/Analog/ReeseBassSynth.js",
    ranges: [[38, 39]],
    isDefault: false,
  },
  {
    name: "FormantSynth",
    path: "./Instruments/Analog/FormantSynth.js",
    ranges: [[52, 54]],
    isDefault: false,
  },
  {
    name: "ChiptuneSynth",
    path: "./Instruments/Analog/ChiptuneSynth.js",
    ranges: [[80, 82]],
    isDefault: false,
  },
  {
    name: "SlapBassSynth",
    path: "./Instruments/Decay/SlapBassSynth.js",
    ranges: [[36, 37]],
    isDefault: false,
  },
];

// --- INDEX.TS AUTO-GENERATOR ---
let registryCode = `/**
 * @fileoverview AUTO-GENERATED BY VITE CONFIG
 * 
 * @reason Central Registry & Export Hub.
 * This file is automatically generated by \`vite.config.ts\` to ensure that 
 * the \`MasterInstrumentMap\` correctly initializes all 16 default GM synthesizers 
 * at the correct index ranges. It acts as the primary NPM package entry point.
 */\n`;
registryCode += `import { decodeBinary, encodeToBinary, encodeToSoA } from './RLO-Transpiler.js';\n`;
registryCode += `import { RLOCore as BaseCore } from './Core/RLOCore.js';\n`;
registryCode += `import { RLOMusicPlayer as BaseMusicPlayer } from './Players/RLOMusicPlayer.js';\n`;
registryCode += `import { RLOGameEngine as BaseGameEngine } from './Players/RLOGameEngine.js';\n`;
registryCode += `import { createInstrumentMap, extendInstrumentMap, createDirectMap, SilentSynth } from './Core/InstrumentMap.js';\n`;
registryCode += `import type { ISynthInstrument } from './Instruments/ISynthInstrument.js';\n`;

const uniquePaths = [...new Set(SYNTH_MODULES.map((m) => m.path))];
uniquePaths.forEach((p) => {
  const synthsInPath = SYNTH_MODULES.filter((m) => m.path === p).map(
    (m) => m.name,
  );
  registryCode += `import { ${synthsInPath.join(", ")} } from '${p}';\n`;
});

registryCode += `\n// Export all synthesizers (including optional ones) for NPM users\n`;
registryCode += `export { ${SYNTH_MODULES.map((m) => m.name).join(", ")} };\n\n`;

registryCode += `const defaultMapModules = [\n`;
SYNTH_MODULES.filter((m) => m.isDefault).forEach((m) => {
  m.ranges.forEach(([start, end]) => {
    registryCode += `  { synth: new ${m.name}(), start: ${start}, end: ${end} },\n`;
  });
});
registryCode += `];\n`;
registryCode += `const defaultMap = createInstrumentMap(defaultMapModules);\n\n`;

registryCode += `const retroMap = createInstrumentMap([\n`;
registryCode += `  { synth: new ChiptuneSynth(), start: 0, end: 127 },\n`;
registryCode += `  { synth: new DrumSynth(), start: 128, end: 128 }\n`;
registryCode += `]);\n\n`;

registryCode += `export { decodeBinary, encodeToBinary, encodeToSoA, createInstrumentMap, extendInstrumentMap, createDirectMap, SilentSynth, defaultMap as MasterInstrumentMap, defaultMap as StandardInstrumentMap, retroMap as RetroInstrumentMap };\n`;
registryCode += `export class RLOCore extends BaseCore { constructor(ctx: AudioContext, customMap?: ISynthInstrument[]) { super(ctx, customMap || defaultMap); } }\n`;
registryCode += `export class RLOMusicPlayer extends BaseMusicPlayer { constructor(ctx: AudioContext, customMap?: ISynthInstrument[]) { super(ctx, customMap || defaultMap); } }\n`;
registryCode += `export class RLOGameEngine extends BaseGameEngine { constructor(ctx: AudioContext, customMap?: ISynthInstrument[]) { super(ctx, customMap || defaultMap); } }\n`;

// Safely write to disk only if changed (prevents infinite Vite dev loops)
const outPath = path.resolve(process.cwd(), "./index.ts");
let needsWrite = true;
if (fs.existsSync(outPath)) {
  if (fs.readFileSync(outPath, "utf-8") === registryCode) {
    needsWrite = false;
  }
}
if (needsWrite) fs.writeFileSync(outPath, registryCode);
// -------------------------------

/**
 * STANDARD NPM LIBRARY CONFIGURATION
 * Preserves all features, exports standard ES and UMD modules, and creates Source Maps.
 */
export default defineConfig({
  define: {
    __ENABLE_TRANSPILER__: true,
    __ENABLE_MUSIC_PLAYER__: true,
    __ENABLE_GAME_ENGINE__: true,
    __ENABLE_WORKER_METRONOME__: false,
    __ENABLE_NOTE_PARSER__: true,
    __ENABLE_STRICT_GC__: true,
    __ENABLE_MIDI_DEBUG__: true,
  },
  build: {
    target: "es2020",
    minify: "terser",
    terserOptions: customTerserOptions,
    sourcemap: true,
    lib: {
      entry: "./index.ts",
      name: "RLOEngine",
      formats: ["es", "umd"],
      fileName: (format) =>
        format === "es" ? "rlo-engine.min.js" : "rlo-engine.min.umd.js",
    },
  },
  plugins: [
    {
      name: "force-terser-on-es-module",
      apply: "build" as const,
      enforce: "post" as const,
      async renderChunk(code: string, chunk: any, options: any) {
        if (options.format === "es") {
          const result = await minify(code, customTerserOptions as any);
          return { code: result.code as string, map: result.map as any };
        }
        return null;
      },
    },
  ],
});
